import { Room } from './types';

export const ROOMS: Record<string, Room> = {
  entrance: {
    id: 'entrance',
    name: '동굴 입구',
    description: [
      '',
      '  어둠 속에서 은은한 빛이 당신을 이끕니다...',
      '  고대의 현자가 동굴 입구에서 기다리고 있습니다.',
      '',
    ],
    exits: [],
    aiInterpretation: false,
  },
  synthesis: {
    id: 'synthesis',
    name: '종합 풀이',
    description: [
      '',
      '         .  *  .    .   *   .  *  .    .',
      '     *        .        .        .        *',
      '  ╔═══════════════════════════════════════════╗',
      '  ║           종  합    풀  이               ║',
      '  ║           綜  合    풀  이               ║',
      '  ╚═══════════════════════════════════════════╝',
      '',
      '  모든 기운이 하나로 모이는 곳입니다.',
      '  현자가 그대의 사주를 펼쳐 큰 그림을 그립니다...',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'detail', label: '사주 상세 분석' },
      { direction: '2', roomId: 'luck', label: '운세의 방' },
      { direction: '3', roomId: 'compatibility', label: '궁합의 방' },
    ],
    aiInterpretation: true,
  },
  detail: {
    id: 'detail',
    name: '사주 상세 분석',
    description: [
      '',
      '    🌿 목    🔥 화    ⛰️  토    ⚔️  금    💧 수',
      '  ╔═══════════════════════════════════════════╗',
      '  ║      사  주    상  세    분  석           ║',
      '  ║      오행 · 십성 · 원국 구조              ║',
      '  ╚═══════════════════════════════════════════╝',
      '',
      '  다섯 개의 화로가 각각 다른 빛으로 타오르고,',
      '  열 개의 석상이 화로 사이에서 서로를 바라봅니다.',
      '  현자가 사주의 깊은 구조를 읽어냅니다...',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'synthesis', label: '종합 풀이' },
      { direction: '2', roomId: 'luck', label: '운세의 방' },
      { direction: '3', roomId: 'compatibility', label: '궁합의 방' },
    ],
    aiInterpretation: true,
  },
  luck: {
    id: 'luck',
    name: '운세의 방',
    description: [
      '',
      '    ════ 과거 ═══╦═══ 현재 ═══╦═══ 미래 ════',
      '  ╔═══════════════════════════════════════════╗',
      '  ║           운  세  의    방                ║',
      '  ╚═══════════════════════════════════════════╝',
      '',
      '  긴 회랑에 시간의 강이 흐르고 있습니다.',
      '  강물 위에 과거와 미래의 운이 떠다닙니다.',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'synthesis', label: '종합 풀이' },
      { direction: '2', roomId: 'detail', label: '사주 상세 분석' },
      { direction: '3', roomId: 'compatibility', label: '궁합의 방' },
    ],
    aiInterpretation: true,
  },
  compatibility: {
    id: 'compatibility',
    name: '궁합의 방',
    description: [
      '',
      '         ◐ ════════════════════ ◑',
      '  ╔═══════════════════════════════════════════╗',
      '  ║           궁  합  의    방                ║',
      '  ╚═══════════════════════════════════════════╝',
      '',
      '  두 개의 거울이 마주 보며 기운을 비추고 있습니다.',
      '',
      '  현자: "궁합을 보려면 상대방의 정보가 필요하다네."',
      '',
      '  한 줄 입력: 이름 생년월일 [양력/음력] 시간 성별',
      '  예) 홍길동 1992-05-20 14:30 여',
      '  예) 홍길동 1992.5.20 음력 모름 남',
      '',
      '  또는 이름만 입력하면 하나씩 물어봅니다.',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'synthesis', label: '종합 풀이' },
      { direction: '2', roomId: 'detail', label: '사주 상세 분석' },
      { direction: '3', roomId: 'luck', label: '운세의 방' },
    ],
    aiInterpretation: false,
  },
};
