import { Room } from './types';

export const ROOMS: Record<string, Room> = {
  entrance: {
    id: 'entrance',
    name: '동굴 입구',
    description: [
      '',
      '  어둠 속에서 은은한 빛이 당신을 이끕니다...',
      '  고대의 현자가 동굴 입구에서 기다리고 있습니다.',
      '',
    ],
    exits: [],
    aiInterpretation: false,
  },
  cave: {
    id: 'cave',
    name: '사주의 동굴',
    description: [
      '',
      '  [사주의 동굴]에 들어섰습니다.',
      '  동굴 벽면에서 신비로운 빛이 흘러나옵니다.',
      '  현자가 눈을 감고 당신의 사주를 펼칩니다...',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'elements', label: '오행·십성의 방' },
      { direction: '2', roomId: 'luck', label: '운세의 방' },
      { direction: '3', roomId: 'synthesis', label: '종합 풀이' },
      { direction: '4', roomId: 'compatibility', label: '궁합의 방' },
    ],
    aiInterpretation: true,
  },
  elements: {
    id: 'elements',
    name: '오행·십성의 방',
    description: [
      '',
      '  [오행·십성의 방]에 들어섰습니다.',
      '  다섯 개의 화로가 각각 다른 빛으로 타오르고,',
      '  열 개의 석상이 화로 사이에서 서로를 바라보고 있습니다.',
      '  오행의 기운과 십성의 관계가 하나로 얽혀 회전합니다.',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'cave', label: '사주의 동굴' },
      { direction: '2', roomId: 'luck', label: '운세의 방' },
      { direction: '3', roomId: 'synthesis', label: '종합 풀이' },
      { direction: '4', roomId: 'compatibility', label: '궁합의 방' },
    ],
    aiInterpretation: true,
  },
  luck: {
    id: 'luck',
    name: '운세의 방',
    description: [
      '',
      '  [운세의 방]에 들어섰습니다.',
      '  긴 회랑에 시간의 강이 흐르고 있습니다.',
      '  강물 위에 과거와 미래의 운이 떠다닙니다.',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'cave', label: '사주의 동굴' },
      { direction: '2', roomId: 'elements', label: '오행·십성의 방' },
      { direction: '3', roomId: 'synthesis', label: '종합 풀이' },
      { direction: '4', roomId: 'compatibility', label: '궁합의 방' },
    ],
    aiInterpretation: true,
  },
  synthesis: {
    id: 'synthesis',
    name: '종합 풀이',
    description: [
      '',
      '  [종합 풀이의 전당]에 들어섰습니다.',
      '  모든 기운이 하나로 모이는 곳입니다.',
      '  현자가 깊은 숨을 내쉬며 말합니다...',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'cave', label: '사주의 동굴' },
      { direction: '2', roomId: 'elements', label: '오행·십성의 방' },
      { direction: '3', roomId: 'luck', label: '운세의 방' },
      { direction: '4', roomId: 'compatibility', label: '궁합의 방' },
    ],
    aiInterpretation: true,
  },
  compatibility: {
    id: 'compatibility',
    name: '궁합의 방',
    description: [
      '',
      '  [궁합의 방]에 들어섰습니다.',
      '  두 개의 거울이 마주 보며 서로의 기운을 비추고 있습니다.',
      '  현자가 미소를 지으며 말합니다...',
      '',
      '  현자: "궁합을 보려면 상대방의 정보가 필요하다네."',
      '  현자: "상대방의 이름을 알려주시오."',
      '',
    ],
    exits: [
      { direction: '1', roomId: 'cave', label: '사주의 동굴' },
      { direction: '2', roomId: 'elements', label: '오행·십성의 방' },
      { direction: '3', roomId: 'luck', label: '운세의 방' },
      { direction: '4', roomId: 'synthesis', label: '종합 풀이' },
    ],
    aiInterpretation: false,
  },
};
